### ISSUE TITLE
Specific blocks to use/break/place

### ISSUE THREAD

**Issue by AykaSova** [BlackAce21/FakePlayerFix#1]
Dear Mathew! 
In the first place I would thank you for the brilliant work saving our souls from hell of PermEx and fakeplayers. Your tiny plugin is an example of small code with great significance!
In the second place I would probably thank you again and again! :)

My question is a probability for making differenciation in certain blocks for, say, breaking  by [BuildCraft]. It was a great idea in PermEx (but done nothing for it!): - -essentials.build.break.6241 to prevent for example destroying of monster spawners by quarry.

I'm realising it a big issue. You plobably did let this plugin away forever.
But probably you may show me the clue where I can dig into your code to make tiny but important changes?

Think for a lot of people would appreciate this significant feature!

Thak you very much again and sorry for my broken English!

**Comment by BlackAce21** [comment]
Adding such a feature wouldn't be difficult or even that time consuming,
however for the example you gave, it would mean that the quarry would dig
until it hit that block and then it would simply pause at that block and be
unable to continue because if the break event isn't allowed it will simply
freeze it. It would not make such blocks unbreakable like bedrock which is
skipped over. Depending on how the quarry works it would have to either be
a change to the meta data for the monster spawners to make them resemble
bedrock, or a straight addition to the mod with the quarry. I don't know
what functionality you are looking for here specifically, but if this is
what you wish I could make it happen.
